#!/bin/bash
#SBATCH --job-name=fastq
#SBATCH --mail-type=ALL # Valid values: BEGIN, END, FAIL, REQUEUE and ALL.
#SBATCH --mail-user=cdong1@tulane.edu
#SBATCH --output=/lustre/project/svanbael/bolivar/Mimulus_sequences/mim3_bioinformatics/ddRAD/2_fastQC/fastQC_files/fastqc.out
#SBATCH --error=/lustre/project/svanbael/bolivar/Mimulus_sequences/mim3_bioinformatics/ddRAD/2_fastQC/fastQC_files/fastqc.err
#SBATCH --time=0-24:00:00
#SBATCH --cpus-per-task=20  #: Cpus per Task
#SBATCH --nodes=1            #: Number of Nodes
#SBATCH --array=1-45  # Job array (1-n) when n is number of unique samples that came off the sequencer

#### load modules###
module load fastqc
module load gnuparallel
module load anaconda3
unset PYTHONPATH
source activate /lustre/project/kferris/conda/conda-envs/qc_env # This is to load a virtual environment from which to load 'multiqc'
###########################################################################################
<<Note_toUser
The script below serves to perform most of the QC steps needed before aligning and 
variant calling.

Softlinks to files only need to be made once and it's best not to work with the original 
fastq or fastq.gz files. 

FastQC will generate QC reports for each sequence file. This step is very slow to run.
MultiQC will then take the fastQC output files and compile them into a single QC report.
Note_toUser
###########################################################################################

echo "Start Job"

### Create folders fastQC_files and multiqc in 2_fastQC FIRST
### set working directory (file output directory) ###
cd /lustre/project/svanbael/bolivar/Mimulus_sequences/mim3_bioinformatics/ddRAD/2_fastQC/

### creating softlinks for fastq files to current directory ###
ln -s =/lustre/project/svanbael/bolivar/Mimulus_sequences/mim3_bioinformatics/ddRAD/1_data/* .

### running FastQC ###
echo "Start FastQC"
for fastq in /lustre/project/svanbael/bolivar/Mimulus_sequences/mim3_bioinformatics/ddRAD/2_fastQC/*;do
fastqc $fastq -o /lustre/project/svanbael/bolivar/Mimulus_sequences/mim3_bioinformatics/ddRAD/2_fastQC/fastQC_files/
done
echo "End FastQC"

### running MultiQC (using Fastqc files) ###
echo "Start MultiQC"
multiqc . -o /lustre/project/svanbael/bolivar/Mimulus_sequences/mim3_bioinformatics/ddRAD/2_fastQC/multiqc
echo "End MultiQC"

### Unsetting environmentc ###
source deactivate
module purge #unloads all module

echo "End Job"
